### ISSUE TITLE
Compiler errors on unity 2017.1 and 2018.2

### ISSUE THREAD

**Issue by Aranir** [fbsamples/oculus-networked-physics-sample#1]
First of all, this is a great learning resource.

Unfortunately, I could not compile it under unity 2017.1 or 2018.2 (latest release).

Which unity version is required for this sample project?

**Comment by mattconte** [comment]
Hi Roger. The project as is requires Unity 5.6.4p1-OC1, which is a beta build that adds lifecycle 2.0 / Dash support. I plan on updating to 2017 or 2018 soon. 

--matt

**Comment by mattconte** [comment]
Hello @Aranir. I have updated the project to Unity 5.6.4p1-OC1, Oculus Utilities 1.27, and Oculus Platform SDK 1.24. From a clean checkout, i can load it into Unity 2017.2.3f1, so i think it should work for you. Please let me know!

**Comment by spiraloid** [comment]
I'm having trouble loading this in unity 2018.3.0b10  any chance it might get updated?

**Comment by mattconte** [comment]
@spiraloid What issues are you running into?

**Comment by spiraloid** [comment]
Thanks for the reply!

We're getting compile errors about namespace security.   It seems like it might be a wider issue with the general oculus integration.  A vanilla project with latest oculus integration from the asset store won't play without compiler errors.

if create a project from this network repo, and let unity up-convert it to 2018.3.0b10,  (and decline importing the latest oculus integration)  the loopback scene will play without error, but the avatar stays in the floor, no hands, no second networked second player etc.

I've installed 2017.4.15f1 and declined updating to the latest oculus integration and it works fine.  So we're back porting and looking at unpacking the nested prefabs and saving the serialization.

Would love it if this example worked on the latest oculus integration in the asset store,  with the latest beta for 2018.3.0b10 (nested prefabs are awesome)

**Comment by spiraloid** [comment]
From a clean checkout and install of Unity 2017.4.16f1
Oculus Utilities 1.27
Oculus Platform SDK 1.24

I get these errors when running the host.exe 

[Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()
