### ISSUE TITLE
2017.4.15f1  missing assets

### ISSUE THREAD

**Issue by spiraloid** [fbsamples/oculus-networked-physics-sample#2]
FYI:  it looks like the two psd files are corrupted that ship with this and cause errors on build.  

Could not create asset from Assets/OvrAvatar/Content/Materials/controller_AO.psd: File could not be read
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions)
Build:BuildHost() (at Assets/Scripts/Editor/Build.cs:23)
Build:BuildAll() (at Assets/Scripts/Editor/Build.cs:51)

Could not create asset from Assets/OvrAvatar/Content/Materials/controller_NM.psd: File could not be read
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions)
Build:BuildHost() (at Assets/Scripts/Editor/Build.cs:23)
Build:BuildAll() (at Assets/Scripts/Editor/Build.cs:51)

**Comment by mattconte** [comment]
Hello, i just updated the project to 2017.4.17f1, and i do not see these errors. Can you test again and re-open if you are still having issues?
