### ISSUE TITLE
2017.4.15f1 build of host and guest will not connect to eachother

### ISSUE THREAD

**Issue by spiraloid** [fbsamples/oculus-networked-physics-sample#3]
I have built all using the build menu and copied the folder to another machine. 

both machines have oculus accounts, are friends and in a party together.   when I run the host, the cubes fall, but cannot be picked up anything, nor does space reset.    same behavior on the guest.exe.
the spectator window is spewing null refs (for both host.exe and guest.exe). 

running the build looback.exe works fine however...  no spew, hand interactions work etc.....

has this example depreciated? or am I missing some step to get the hose and guest to run correctly?
or perhaps, there is a working example elsewhere I should be using?

any pointers would be appreciated.

-bay

[Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

 [Exception] : NullReferenceException: Object reference not set to an instance of an object
Avatar.UpdatePointingLine (.HandData& hand)
Avatar.UpdateCurrentState (.HandData& hand)
Avatar.UpdateHand (.HandData& hand, .PoseFrame frame)
Avatar.Update ()

**Comment by spiraloid** [comment]
After reinstalling various versions of unity, oculus utilities and platform sdk’s it seems like this awesome example has depreciated below the minimum spec for the santa cruz.   Seems like it would be a perfect fit for free roaming games.  Any chance it will get updated?

**Comment by mattconte** [comment]
@spiraloid I can repro. Looks like the neither Guest nor Host's Start() methods are getting called. I will have to debug this.

**Comment by mattconte** [comment]
This is fixed with the latest commit.
