### ISSUE TITLE
smallest three quaternion with uint

### ISSUE THREAD

**Issue by kevincastejon** [fbsamples/oculus-networked-physics-sample#5]
it's more likely a noob question than an issue,
I figured out by digging the code that the Snapshot quaternion compressions methods (smallest three) are outputing/inputing uint, isn't uint  the same size as float?
By reading [this article](https://gafferongames.com/post/snapshot_compression/) i've seen that it is supposed to go down to 29bits for a quaternion, does these compressions methods follow the same path and give the same result as the ones in the article?
From what I can tell the size result is the same with Quaternion (4 float) and a compressed one (with 4 uint)

**Comment by gafferongames** [comment]
The snapshot is not the wire format. Look at the delta compression method that takes two snapshots and writes out the difference...

**Comment by kevincastejon** [comment]
sorry but I can't find that piece of code you're talking about... could you tell me in which file the state delta is done?
(is there any place better than github to discuss it? did not found discord or else, so I'm sorry to pollute the repo...)

**Comment by gafferongames** [comment]
Look at the WriteStateUpdatePacket function

**Comment by kevincastejon** [comment]
thx
